### ISSUE TITLE
SettlementRepositoryTest 테스트 실패 이슈

### ISSUE THREAD

**Issue by tkddn204** [CoolPeace-yanolza/backend#100]
# 설명
- 전체 테스트를 진행 중에 SettlementRepositoryTest에 다음과 같은 테스트 실패가 발생했습니다.
![image](https://github.com/CoolPeace-yanolza/backend/assets/6284140/5a0039fd-1db1-4afd-b558-70cde3246cf5)
![image](https://github.com/CoolPeace-yanolza/backend/assets/6284140/44cdcb5f-32ab-4db4-8722-6a18b139faed)

# 원인
- 다른 테스트에서 해당 DB 테이블과 관련된 테이블을 저장할 경우 ID가 고정적으로 1이 아닌 다른 값으로 충분히 ID 값이 변동될 수 있는 가능성을 내포하고 있습니다.
- 따라서 해당 테스트는 실제 DB를 사용하는 다른 테스트들과 같이 진행할 때 실패할 수도, 성공할 수도 있을 것입니다.

# 해결 제안
- assert 체크 시 id 값을 체크하지 않도록 변경하는 것이 좋을 것 같습니다.

**Comment by KwonJuHwan** [comment]
id 삭제후 PR 머지하였습니다
