### ISSUE TITLE
정산과 대시보드 테스트의 요청에 Authorization 헤더 추가 요청

### ISSUE THREAD

**Issue by tkddn204** [CoolPeace-yanolza/backend#112]
# 설명
- 스웨거를 보던 중에 정산과 대시보드 쪽에 권한 자물쇠가 붙어있지 않은 것을 발견했습니다.
	![image](https://github.com/CoolPeace-yanolza/backend/assets/6284140/c111fa7a-8024-402e-8aa8-d4f6d5868856)
- 다음과 같이 자물쇠가 없습니다.
	![image](https://github.com/CoolPeace-yanolza/backend/assets/6284140/2cd7489d-0f12-435f-9fd1-f33bdd9abc11)

- docs 안의 테스트 코드를 보니 요청에 Authorization 헤더를 붙이지 않으셨던 것 같습니다.
- 문서의 통일성을 위해 권한 관련 헤더를 요청에 붙여주시면 감사하겠습니다.
- 권한 관련 헤더가 없음에도 테스트가 통과됐던 건 `@WithMockUser` 때문에 권한이 통과되었던 것으로 추측됩니다.

# 작업내용
- [ ] 정산 컨트롤러 테스트에 Authorization 헤더 추가
- [ ] 대시보드 컨트롤러 테스트에 Authorization 헤더 추가

**Comment by KwonJuHwan** [comment]
시큐리티 테스트를 위한 테스트가 아니므로,  시큐리티의 영향을 받지 않는 유닛 테스트를 위해 @WithMockUser를 사용하였습니다. 통일성을 위해서 Authorization 헤더를 추가해야 한다고 한다면, 통합 테스트 환경이 아닌 유닛 테스트에선 Authorization 헤더를 어떻게 설정하면 좋을까요? 기존의 제가 해왔던 방식이랑 많이 달라서 알려주시면 감사하겠습니다. 다른 Rest docs 테스트 코드에서 헤더를 위해 작성해주신 코드들은 통합 테스트에서만 돌아가게끔 구현되어 있어서 요청드립니다.

**Comment by tkddn204** [comment]
저도 유닛테스트로 진행해 본 적이 없다보니 알아보느라 시간이 좀 걸렸네요 😅
코드 적용 방식이 어떻게 되는지 원래 코드를 찾아가며 알아본 결과 단순하게 다음과 같이 설정하면 된다는 것을 알게 되었습니다.
아래는 예시코드입니다.

```java
private static final String MOCK_AUTHORIZATION_HEADER = "Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIyIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNvb2xwZWFjZSIsImlhdCI6MTcwNDYzODY5NSwiZXhwIjoxNzA0Njc0Njk1fQ.Re2QfSHVBJ9gKq8rCpv8wlvSuDS80jwEjHgGIxg840Og1ng6R_cozWOgw_eU9hgoYW0NUIAZLW322scfkUCRvQ";

//when,then
        mockMvc.perform(RestDocumentationRequestBuilders
                        .get("/v1/dashboards/{accommodation_id}/reports/month", 1L)
                        .header(HttpHeaders.AUTHORIZATION, MOCK_AUTHORIZATION_HEADER))
```

위와 같이 단순하게 헤더만 달면 알아서 헤더 모양을 인식해서 시큐리티 설정을 달아주더라구요!
덕분에 저도 두루뭉실하게만 알던 사실을 알게되어서 좋았습니다.
